### ISSUE TITLE
Importing  LatticeDynamics.jl package to Jupyter notebook

### ISSUE THREAD

**Issue by nicodemosvarnava** [jgwillingham/LatticeDynamics.jl#1]
How can I add the package to my Jupyter notebook?

When I type
]add https://github.com/jgwillingham/LatticeDynamics.jl
I get an error:
could not find project file in package at `https://github.com/jgwillingham/LatticeDynamics.jl` maybe `subdir` needs to be specified

**Comment by jgwillingham** [comment]
I never bothered to setup project files for this so I don't think using the julia package manager will work. But if you clone the repo, you can point julia to it with `push!(LOAD_PATH, "\path\to\your\local\repo")`. Then `using LatticeDynamics` ought to work. 
If you don't have them already you will need to `add GSL` and `add ProgressMeter` too.
