### ISSUE TITLE
Non-zero acoustic modes at the Gamma point

### ISSUE THREAD

**Issue by nicodemosvarnava** [jgwillingham/LatticeDynamics.jl#2]
Thank you for the example file.  

I used the example as a template for NbSe2 but the acoustic modes are not zero when I consider nearest neighbor interactions. I wonder if I am doing something wrong

`
unitCell = [ ["Nb", [0.0,0.0,0.50]],
             ["Se", [2/3,1/3,0.41]],
             ["Se", [2/3,1/3,0.59]] ]

a_const =3.4739; c_const=20.0
a1=[a_const,0.0,0.0]
a2=[-a_const/2,sqrt(3)*a_const/2,0.0] 
a3=[0.0,0.0,c_const] 
latticeVectors = [a1, a2, a3]
cutoff = 5.0

NbSe2 = Crystal(unitCell, latticeVectors, cutoff);

nbnb_params   = (-0.0, -0.0)
se1se1_params = (-0.0, -0.0); se2se2_params = se1se1_params
nbse1_params  = (-0.1, -0.0); nbse2_params  = nbse1_params
se1se2_params = (-0.0, -0.0)

couplings = [[nbnb_params,  nbse1_params,  nbse2_params],
             [nbse1_params, se1se1_params, se1se2_params],
             [nbse2_params, se1se2_params, se2se2_params]];

G = 2π/a_const
Γ = [0.0, 0.0, 0.0]
M = [1*G/2, 0.0, 0.0]
K = [1*G/3, 1*G/3, 0.0]

qPath, qPathParts = buildPath([Γ, M, K, Γ], 100)
qLabels = ["Γ", "M", "K","Γ"]
disp, modes = getDispersion(qPath, NbSe2, couplings);
plotDispersion(disp, qPathParts, qLabels)
`

**Comment by jgwillingham** [comment]
Fixed it. It was just a simple problem of giving the two Se atoms different labels. If you pull the changes, it should work now
